// Danh sách ngân hàng Việt Nam
const VIETNAM_BANKS = [
    'ABBANK',
    'ACB',
    'Agribank',
    'ANZ',
    'BacA Bank',
    'BAO VIET BANK',
    'BIDV',
    'BVBank',
    'CBBANK',
    'CIMB',
    'Citibank',
    'COOPBANK',
    'DBS',
    'Eximbank',
    'GPBank',
    'HDBank',
    'HongLeong',
    'HSBC',
    'KBank',
    'KienLongBank',
    'LienVietPostBank',
    'MB',
    'MSB',
    'Nam A Bank',
    'NCB',
    'OCB',
    'OceanBank',
    'PGBank',
    'PublicBank',
    'PVcomBank',
    'Sacombank',
    'SCB',
    'SeABank',
    'SGB',
    'SHB',
    'Shinhan',
    'StandardChartered',
    'Techcombank',
    'TPBank',
    'UOB',
    'VIB',
    'VietABank',
    'VietBank',
    'VietCapital Bank',
    'Vietcombank',
    'VietinBank',
    'VPBank',
    'Woori'
];
